src/ruby_miniblog/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  root :to => "homes#index"

  resources :users
  resources :logins
  resources :posts do 
    member do
      post "update_comment"
    end
  end
  resources :comments

  get "sign_up"=>"users#new", :as => "sign_up"
  get "log_out" => "logins#destroy", :as => "log_out"
  get "log_in" => "logins#new", :as => "log_in"
  get "homes/" =>"homes#index"
  get "posts/:id" => "post#show"
  get "/users/:id" => "users#update"

end

src/ruby_miniblog/app/models/comment.rb
class Comment < ActiveRecord::Base 
 belongs_to :user
end

src/ruby_miniblog/app/models/post.rb
class Post < ActiveRecord::Base 
  belongs_to :user
  has_many :comments

  validates :description, length: { maximum: 255 }
  validates :content, length: { minimum: 255 }
  validates_uniqueness_of :title

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/system/posts/images/default/:style/missing.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

# sort order by created_at
  default_scope  { order(:created_at => :desc) }

# View all post of user  
  scope :post_of_user, ->(user_post) {where("user_id = #{user_post}")}

# update count view for post
def update_count_view(id,count_view)
 post = Post.find id
 post = post.update(:count_view => count_view + 1)
  
end

end
 

src/ruby_miniblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  layout "application_v1"
  
  helper_method :current_user
  
  before_action :all_post

private
	def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
      
	end

  def all_user
    @user = User.all

  end
  
  def all_post
    @title = "Home"
    add_breadcrumb "Home", :homes_path
    @post_read_mores = Post.where("count_view > 0").order("count_view desc").limit(4)
    @posts = Post.all.paginate(:page => params[:page], :per_page => 10)

  end
end

src/ruby_miniblog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

layout false

before_action :set_comment, only: [:show, :edit, :update, :destroy]

def new
	@comment = Comment.new

end

def show
	
	
end

def edit
	render :partial =>false

end

def update
	render :partial =>false
	if @comment.update(comment_params)
       redirect_to @post, :comment=>"Update comment successfully"
    else
       redirect_to @post
    end
	
end
# Add new comment
def create
	@post = Post.find(params[:comment][:post_id])
	@comment = Comment.new(comment_params)
	if @comment.save
		redirect_to @post, :comment=>"Post comment successfully"
	else
		redirect_to @post
    end
end
    
def destroy
	
    if @comment.destroy
      redirect_to @post, :comment=>"Delete comment successfully"
    else
      redirect_to @post, :comment=>"Delete comment unsuccessfully"
    end
end

private
# find comment

def set_comment
	@comment = Comment.find(params[:id])
	@post = Post.find(@comment.post_id)
	
end

# set params for comment
def comment_params
	params.require(:comment).permit(:content,:post_id,:user_id)
	 	
end
end

src/ruby_miniblog/app/controllers/logins_controller.rb
class LoginsController < ApplicationController

def new
	add_breadcrumb "Login", :log_in_path
	@title = "Login"
	
end

def create
#byebug
	user = User.authenticate(params[:username], params[:password])
	if user
		session[:user_id] = user.id
		redirect_to homes_path, :login => "Logged in!"
	else
		flash[:login] = "Invalid username or password"
		render "new"
	end
end

def destroy
	session[:user_id] = nil
	redirect_to homes_path, :notice_out => "Logged out!"

end

end

src/ruby_miniblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  skip_before_action :verify_authenticity_token

  def index
    @title = "Posts"
    add_breadcrumb "Posts", :posts_path
    @post_read_mores = Post.where("count_view > 0").order("count_view desc").limit(4)
    if params[:user_post]
       @posts = Post.post_of_user(params[:user_post]).paginate(:page => params[:page], :per_page => 10)
       flash[:count] = @posts.count
       flash[:name] = User.select(:id,:username).find_by_id(params[:user_post])
       
    elsif current_user.id
       @posts = Post.post_of_user(current_user.id).paginate(:page => params[:page], :per_page => 10)

    else
      @posts = Post.all.paginate(:page => params[:page], :per_page => 10)

    end
  end

  def show
    @title =  @post.title
    add_breadcrumb "Post", :post_path
    @comments = @post.comments
    @post.update_count_view(@post.id, @post.count_view)
    @post_of_users = Post.post_of_user(@post.user_id)

  end

  def new
     @title =  "Create post"
     add_breadcrumb "Create post", :new_post_path
     @post = Post.new
  
  end

  def edit
   @title =  "Edit | " << @post.title
   add_breadcrumb "Edit post", :edit_post_path

  end

  def update_comment
    
    @post = Post.find(params[:comment][:post_id])
    comment = Comment.find(params[:comment][:id])
    if comment.update(:content =>params[:comment][:content])
      redirect_to @post
    end
  end

  def create
    #byebug
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to homes_path, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }   
      end
    end
  end

  def destroy
    if !@post.comments
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
    else
    redirect_to posts_url, notice: 'The post has a comment and then not deleted.'
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_post
      @post = Post.find(params[:id])

  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
      params.require(:post).permit(:title, :content, :description, :user_id,:image)
      
  end
end

src/ruby_miniblog/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit,:update,:show]

  skip_before_action :verify_authenticity_token

  def index
    add_breadcrumb "All users", :users_path 
    @users = User.search_by_user(params[:search])

  end

  def new
    @title = "Signup"
    add_breadcrumb "Signup", :sign_up_path
    @user = User.new

  end

  def edit 
    @title = "Edit | " << @user.username
    add_breadcrumb "Edit profile", :edit_user_path

  end

  def show
    add_breadcrumb "Change password", :user_path

  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to log_in_path, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def update
    if params[:flag].present? 
      user = User.authenticate(current_user.username, params[:user][:password])
      if user
        @user.update(user_edit_params)
        redirect_to homes_path, user_update: 'User was successfully updated.'
      else
        flash[:user_update_f] = "Password current not validate, please entry password"
        render "edit"
      end
    else
      user = User.authenticate(current_user.username, params[:user][:password_old])
      if user 
        @user.update(user_change_password_params)
        flash[:change] = "Change password successfully"
        redirect_to user_path
      else
        flash[:change] = "Password current incorrect"
        redirect_to user_path
      end
    end
  end

  #get strong params 
  private

  def set_user
    @user = User.find(params[:id])

  end

  def user_params
    params.require(:user).permit(:email, :username, :first_name, :last_name, :display_name, :birthday, :avatar,:gender, :status, :password, :password_salt)

  end

  def user_edit_params
    params.require(:user).permit(:email, :username, :first_name, :last_name, :display_name, :birthday, :avatar,:gender,:address,:password, :password_salt)

  end

  def user_change_password_params
    params.require(:user).permit(:password, :password_salt)
    
  end

end

src/ruby_miniblog/app/helpers/users_helper.rb
module UsersHelper

	def genders
		@genders = [['Male', '0'], ['Female', '1'], ['Other','2']]
		
	end

	def active_status
		@status = [['Active', '1'], ['No', '0']]

	end
end

src/ruby_miniblog/app/views/homes/index.html.erb
<div class="col-md-12">
  <% @posts.each_with_index do |post, idx| %>
  <% if idx % 2 == 0 %>
  <div class="row">
    <%end %>
    <div class="col-md-6 portfolio-item">
      <div class="col-sm-4">
        <a href="#">
          <%= image_tag post.image.url(:thumb), :class => 'img-thumbnail' %>
        </a>
     </div>
     <div class="col-sm-8">
      <div class="dropdown badge pull-right">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b> </a>
        <ul class="dropdown-menu">
          <li>
          <span class ="left_readmore"><%=image_tag "read_more.png"%>
          <a href=<%= post_path(post)%>>Read more</a>
          </span>
          </li>
          <% if current_user && current_user.id == post.user_id%>
          <li>
            <span class ="left_readmore"><%=image_tag "edit.png"%>
            <%= link_to "Edit", edit_post_path(post)%>  
            </span>
          </li>
          <li>
          <span class ="left_readmore"><%=image_tag "delete.png"%> 
            <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure?" }%>
          </span>
          </li>
          <%end%>
        </ul>
      </div>
      <div class="title">
        <span class="icon-bar"></span>
        <a href="#"><%= link_to post.title.capitalize, post%></a>
      </div>
      <div class="date"> <%= date_format(post.created_at) %> | Author: <a href="#"><%= post.user.username%></a></div>
      <p class="text-justify">
       <%= post.description %>
     </p>
   </div>                
 </div>
 <% if idx % 2 != 0 %>
</div> 
<%end %>
<%end%>
<%if @posts.count%2!=0 %>
</div>
<%end%>
<div class="row text-center">
  <div class="col-lg-12">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
 </div>
</div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $(".dropdown-toggle").dropdown();
  });  
</script>

src/ruby_miniblog/app/views/layouts/application_v1.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <title><%=@title%></title>
  <meta name="generator" content="Bootply" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>
  <!-- Header -->
  <%= render "layouts/shared/header"%>
  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          <ul class="breadcrumb">
          <li><a href=<%=homes_path%>><%=image_tag("home.png", :class=>"top_image")%></a></li>
            <li><%= render_breadcrumbs %></li>
          </ul>
        </h1>
      </div>
    </div>
    <div class ="row">
      <%= yield%>
      <!--content-->
    </div>      
  </div>
  <!-- Footer -->
  <%= render "layouts/shared/footer"%>
</body>
</html>

src/ruby_miniblog/app/views/layouts/shared/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-lg-12 text-center">
      <p>Copyright &copy; Your MiniBlog 2015</p>
    </div>
  </div>
</footer>

src/ruby_miniblog/app/views/layouts/shared/_header.html.erb
  <div id="top-nav" class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <div class="navbar-header col-md-3">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/homes"></a>
        </div>
      </div>
      <div class=" navbar-header col-md-5" style="margin-top: 8px;">
        <form role="form" action="/users">

          <div class="input-group">
            <input name="search" class="form-control txtSearch" placeholder="Username, firstname, lastname" type="text">
            <span class="input-group-btn">
              <input class="btn btn-info" value="Search" type="submit">
            </span>

          </div><!-- /input-group -->

        </form>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">  <li class="active"><a href="#">MiniBlog</a>  </li>
          <li class="dropdown">
           <% if current_user %>
           <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
             <i class="commenterAvatar">
               <%= image_tag current_user.avatar.url(:thumb),:class =>'img-thumbnail'%>
             </i>
             Hi <%= current_user.display_name %>
             <span class="caret"></span></a>
             <ul id="g-account-menu" class="dropdown-menu" role="menu">
              <li>
              <span class ="left_readmore"><%=image_tag "post_all.png"%>
              <%= link_to 'All post', posts_path%>
              </span>
              </li>
              <li>
              <span class ="left_readmore"><%=image_tag "post_add.png"%>
              <%= link_to 'New post',new_post_path%>
              </span>
              </li>
              <li>
              <span class ="left_readmore"><%=image_tag "edit.png"%>
              <%= link_to 'Edit Profile', edit_user_path(current_user.id)%>
              </li>
              </span>
              <li>
              <span class ="left_readmore"><%=image_tag "change_pass.png"%>
              <%= link_to 'Change password',user_path(current_user.id)%>
              </span>
              </li>
              <li>
              <span class ="left_readmore"><%=image_tag "list_all_user.png"%>
              <%= link_to 'All user',users_path%>
              </span>
              </li>
            </ul>
            <% else %>
            <%= link_to "Sign up", sign_up_path %>
            <% end %>  
          </li>
          <li>
           <% if current_user %>
           <%= link_to "Logout", log_out_path %>
           <% else %>
           <%= link_to "Log in", log_in_path %>
           <% end %>
         </li>
       </ul>
     </div>
   </div>
 </div>

src/ruby_miniblog/app/views/logins/new.html.erb
<script>
	$(function () { $("input,select,textarea").not("[type=submit]").jqBootstrapValidation(); } );
</script>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<% if flash[:login] %>
			<div class="alert alert-danger" role="alert">
			<button type="button" class="close" data-dismiss="alert">
				<span aria-hidden="true">&times;</span>
				<span class="sr-only">Close</span>
			</button>
			<%= flash[:login] %>
		</div>
		<%end%>
	</div>
</div>
<div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2"> 
	<div class="panel panel-info" >
		<div class="panel-heading">
			<div class="panel-title">Sign In</div>
		</div>     
		<div style="padding-top:30px" class="panel-body" >
			<div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
			<form id="loginform" action=<%=logins_path%> class="form-horizontal" method="post" role="form">
				<div style="margin-bottom: 25px" class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
					<input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username" required >                   
				</div>
				<div style="margin-bottom: 25px" class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
					<input id="login-password" type="password" class="form-control" name="password" placeholder="password" required>
				</div>
				<div class="input-group">
					
				</div>
				<div style="margin-top:10px" class="form-group">
					<div class="col-sm-12 controls">
						<button style="submit" class="btn btn-success" >
							Login
						</button>
						<a id="btn-fblogin" href=<%= homes_path%> class="btn btn-primary">Cancel</a>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 control">
						<div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
							Don't have an account!
							<%= link_to "Sign Up Here", sign_up_path %> 
						</div>
					</div>
				</div>    
			</form>     
		</div>                     
	</div> 
</div>

src/ruby_miniblog/app/views/posts/_form.html.erb
<%= form_for @post, :html => {:multipart => true, :class => "form-horizontal post" } do |f| %>
<% if @post.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>
<div class="col-lg-10">
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control',:required=>"" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description,:rows =>3, :class => 'form-control',:required=>"" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <div class="col-md-3" style="margin-top:10px">
        <div class="fileUpload btn btn-primary">  
          <span>Browse image</span>
          <%= f.file_field :image, :onchange=>"handlerInputFileChange(this)",:class=>"upload"%>
        </div>
        <%= image_tag @post.image.url(:thumb), :class =>'img-thumbnail',:id =>"image-upload", :style=>"width:150px;height:150px;" %>  
      </div> 
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
     <%= f.cktext_area :content, :ckeditor => {:toolbar => 'mini', :customConfig => asset_path('ckeditor/config.js')}%>
   </div>
 </div>
 <div>
  <% if current_user.nil? %>
  <%= f.hidden_field :user_id, value: "" %>
  <%else%>
  <%= f.hidden_field :user_id, value: "#{ current_user.id}" %>
  <%end%>
</div>
<div class="form-group">
  <div class="col-lg-offset-2 col-lg-10">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
    posts_path, :class => 'btn btn-default' %>
  </div>
</div>
</div>
<% end %>
<script>
function handlerInputFileChange(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();

    reader.onload = function (e) {
      $('#image-upload')
      .attr('src', e.target.result);
    };

    reader.readAsDataURL(input.files[0]);
  }
}
</script>

src/ruby_miniblog/app/views/posts/edit.html.erb
<%- model_class = Post -%>
<%= render :partial => 'form' %>

src/ruby_miniblog/app/views/posts/index.html.erb
<% if !params[:user_post].blank?%>
  <h4 class="error top_error">
    <%- model_class = Post -%>
    About <%= flash[:count] %> result of 
    <a href="#"><%= flash[:name].username %></a> post
  </h4>
<%end%>
<% if flash[:notice] %>
<div class="alert alert-success" role="alert">
  <button type="button" class="close" data-dismiss="alert">
    <span aria-hidden="true">&times;</span>
    <span class="sr-only">Close</span>
  </button>
  <%= flash[:notice] %>
</div>
<%end%>
<div class="col-md-12">
  <% @posts.each_with_index do |post, idx| %>
  <% if idx % 2 == 0 %>
  <div class="row">
    <%end %>
    <div class="col-md-6 portfolio-item">
      <div class="col-sm-4">
        <a href="#">
          <%= image_tag post.image.url(:thumb), :class => 'img-thumbnail' %>
        </a>
     </div>
     <div class="col-sm-8">
      <div class="dropdown badge pull-right">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b> </a>
        <ul class="dropdown-menu">
          <li><a href=<%= post_path(post)%>>Read more</a></li>
          <% if current_user && current_user.id == post.user_id%>
          <li>
            <%= link_to "Edit", edit_post_path(post)%>  
          </li>
          <li> 
            <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure?" }%>
          </li>
          <%end%>
        </ul>
      </div>
      <div class="title">
        <span class="icon-bar"></span>
        <a href="#"><%= link_to post.title.capitalize, post%></a>
      </div>
      <div class="date"> <%= date_format(post.created_at) %> | Author: <a href="#"><%= post.user.username%></a></div>
      <p class="text-justify">
       <%= post.description %>
     </p>
   </div>                
 </div>
 <% if idx % 2 != 0 %>
</div> 
<%end %>
<%end%>
<%if @posts.count%2!=0 %>
</div>
<%end%>
<div class="row text-center">
  <div class="col-lg-12">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
 </div>
</div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $(".dropdown-toggle").dropdown();
  });  
</script>

src/ruby_miniblog/app/views/posts/new.html.erb
<%- model_class = Post -%>

<%= render :partial => 'form' %>

src/ruby_miniblog/app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="row">
  <div class="col-sm-12">
    <h6 class="media-heading date detail"><%= date_format(@post.created_at) %> | Author: <a href="#"><%= @post.user.username %></a></h6>
  </div>
  <div class="col-sm-12">
    <div class="col-sm-8">
      <h4 class="text-justify"><%= @post.title%></h4>
      <p class="text-justify"><%= @post.description%></p>
      <p class="text-center"><a href="#"><%= image_tag @post.image.url(:medium) %></a></p>
      <p class="text-justify"><%= raw(@post.content)%></p>
    </div>
    <div class="col-sm-4">
     <div class="well"> Related posts of author <a><%= @post.user.username %></a> <span class="badge pull-right"><%=@post_of_users.count%></span></div>
     <ul class="list-group">
      <%@post_of_users.each do |post_of_user|%>
      <li class="list-group-item">
        <i class="glyphicon">(<%= post_of_user.count_view%>)</i> 
        <small>(<%= date_format(post_of_user.created_at)%>)
        </small> 
        <%=link_to post_of_user.title.capitalize,post_of_user %></li>
        <%end%>
      </ul>
    </div>
  </div>
</div>
<div class="col-sm-12">
  <div class="col-sm-8">
    <div id="allHolder">
      <form action=<%= comments_path%> method="post">
        <div id ="commentsHolder">
          <textarea id ="commentBodyField" rows="3" name="comment[content]" placeholder="Enter your comment..."></textarea>
        </div>
        <div class="postCommentButtonHolder">
          <input hidden name="comment[post_id]" value=<%=@post.id%>></input>
          <% if current_user%>
          <input hidden id="user_id" name="comment[user_id]" value=<%=current_user.id%>></input>
          <%else%>
          <input hidden id="user_id"  name="comment[user_id]" value="0"></input>
          <%end%>
          <button type="submit" id="comment" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>
<div class="col-sm-12">
  <div class="col-sm-8">
    <div class="detailBox">
      <div class="titleBox">
        <label>All Comment</label>
      </div>
      <div class="commentBox">
      </div>
      <div class="actionBox">
        <ul class="commentList">
          <% @comments.each do |comment|%>
          <li>
            <div class="commenterImage">
             <%= image_tag comment.user.avatar.url(:medium) %>
           </div>
           <div class="commentText">
            <cite class="user"><%= comment.user.username%>
              <span class="date sub-text"><%= date_format(comment.created_at)%></span>
            </cite>
            <p class=""><%= comment.content%></p>
            <%if current_user && current_user.id == comment.user_id%>
            <a href="#" data-toggle="modal" data-target="#cm_<%=comment.id%>">Edit</a>
            <%= link_to "Delete", comment_path(comment), method: :delete, data: { confirm: "Are you sure?" } %>
            <div class="modal fade" id="cm_<%=comment.id%>" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Edit comment</h4>
                  </div>
                  <div class="modal-body">
                    <form action=<%= update_comment_post_path%> method="post">
                      <div id ="commentsHolder">
                        <textarea id ="comment_update" rows="3" name="comment[content]"  style="width: 546px;">
                          <%= raw(comment.content.strip)%>
                        </textarea>
                        <input hidden name="comment[post_id]" value=<%=@post.id%>></input>
                        <input hidden name="comment[id]" value=<%=comment.id%>></input>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                      </div>
                    </form>
                  </div>

                </div>
              </div>
            </div>
            <%end%>
          </div>
        </li>
        <%end%>
      </ul>
    </div>
  </div>
</div>
</div>
<div class="col-sm-12">
 <div class="col-sm-8">
  <p>
    <% if current_user.nil? %>
    <%= link_to "Back", homes_path,:class => 'btn btn-xs btn-danger' %>
    <%else%>
    <%= link_to 'Edit', edit_post_path(@post),:class => 'btn btn-default btn-xs' %>
    <%= link_to "Back", posts_path,:class => 'btn btn-xs btn-danger' %>
    <%end%>
  </p>
</div>
</div>
</div>

<script type="text/javascript">
jQuery(function(){
  $("#comment").click(function(){
    $(".error").hide();
    var hasError = false;
    var content = $("#commentBodyField").val();
    var user_id = $("#user_id").val();
    
    if (content == '') {
      $("#commentBodyField").after('<span class="error">Please enter a content.</span>');
      hasError = true;
    }else if (user_id == 0) {
      $("#commentBodyField").after('<span class="error">Please login use comment.</span>');
      hasError = true;
    }

    if(hasError == true) {return false;}
  });
});
</script>